
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: mysql-credentials
data:
  connection: bXktZGItY29ubmVjdGlvbi5leGFtcGxlLmNvbTozMzA2
  password: bXlmYW5jeXBhc3N3b3Jk
  username: bXlmYW5jeXVzZXI=
root@kubernetes-vm:~/workdir# cat sealed_secrets/db-creds-encrypted.yaml 
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    connection: AgBMbh9c8goaLglf6S6/l7hcD7ojDiE6Rd9ml1+iapWkCP8PUnOBQx9bXsCuw9KsKuRACHMM7eZti7AJSD1Q7csjByby3leJq0I+EY+tEqRH1IDl36xBtNF5rxTRLuPvil3JGLxcRc6Rft7dQNePKYYI+B667shgA3rn+beERWuRH5lB8WCNm1se2acAFlvPRgIcP1wFyz5vPIxAS2ftxCkQQYlHwSXklGkDPYfzmipKmYyLMUZAdLCEiA05prCTXk6c81w2MVMjFXd9w+70piM0fIdsDR2dM08CTt8tD+xU7VivxrRZkAuXuRJFxmhLaKQPyPyS/QmKtX9IoXfkmUkqZvPsYz9xmAQdRmxjlosGyVZg/Jsmdpd/NNfO/boPJSE2zy42EW0WEntNk6qNexOnbid+6+Es/Qv75CuclAcxK3sgeznCcViXP7xI9KO76y6jqhtWHKyPtGwEpSJ6lJMAhhuYbiGLDqgynk6E2nx6DA+YVk3f1eef+oQfKBDkv74eTstnlkBufhsr2c6Y/jp8tJtw6n6F4z9brBXNlfWYIGO4yt9ZX2HXPhVmytXrExmV0lOITn7oSCKHV7u53kqGyZtOhZ6Co9+N82VNDEcdGkTzHBC61HbfR2eq4RmQ8VvbsmdgGY7kV/5SSDF8anPiDAHc9hzwfChMmQo+npZbZ0oVyFDy4aatUGKsVd+UeqynnCqsvLPZXaXIGWPRjuzz3FomVPlD6KJzqpkVcbPQM3c=
    password: AgBtSMbFpA2ztc6iL1ICWExKl2pe6wEQPXlmRybWBgHdQx5e23nUQ19rcfco057aH1JrDLmDFFPjFmceqXSTOoXbkvWMXhwC6ogyYJDn0Wq4ZDILJ2dhURCz3mB9vBce3j8sWmdgUYMi8861xkozlU5lrsTrsfqwpQ6SXN8O1kdDSWMFjJJG3sk0oyxoz/tkiRa42CV+QqWY0Wcjlt7o6hQpOFO1g8zrVkLHIJghEmVzLlsOADAZHgHVnjEzV8GLWB+SzcYAhPXSMj4ef6U1b1TwZTjmE/8WcO94pYqvdukHqm/WtvVvCz6SI7n+hVC4iDMNNZyW74EZViA3ai7IzFYm/t1DadvYFtIQpoG2JWXOvhOVTrDeCXY1Z+3hkuyr3kp1McDL+X28dE5S6bvGRTaT9NfiEBUB6NejF1+6dvpiK9bNYfgx70qLE/lmENZ54OaUP5ZO58KxhNWCdsrdyKjE1iB9aiF6pFGJK7Is1geONf68Wz6kbGDSdFzgkWaQFvNOlRNcihxsPGTpdGavU0DNgpXH/0N2PjOWv6TnvqbsMHHbu3gW4TSZm/NB5Hnt2SRFXyKyTID7CMWeHW/0r812PFj3iXCL/N89WwEKch0WmpVlVovkQkt3KqFtvqCy0fr61dTjL2JzFhhMLaxXCJQaVICtOAj7bd1Sveb7lcJcbGltaoSz4oZxNm7iW4ASDdYKcewYz/kI0YkF+tbTnMw=
    username: AgAaXqcCUB0L+eNcqC36WZp0mosmfor1mnbgzp+OTIzeWoGosAfzmN+uqluyv0bSTrnn+JD4bqAExx557t3aohG7rI7mgCQnMBPtTq0gGDpgmJqNTx4rT89u8AbbYOd+FxUZT/2q9qy3Erv6JLho6vw2UKavqwxJe6Cjv3ZzzNw/1M/6dv6qtsCl0WP7AYUBqteoiwt6GTRSQO73JLvgVGvWzBfsszdkXdNP2AKkNXrxgPzunIdax3htnkMQNGsggkFzPlKE9+N11HK/WcO1YaUzx+zppZRWVAG9ZefAPy5qsJwzfAFA4b7JeF4qa76/cd0orUnWWnqsHCV01iUGd2xBgJkAjVPuTlxwqzrQSfFRf+1HJ+uMfFCi7+MD+yPg7yqKJliuny//NpvuH3O1VcpeiYKqISGk6PSayI6s91c6UApz5Qs/0jVlDmdlveOKo9GO/2zR1rVAhAU6QHfdQ8xotllP1Cv6tnN6bklmRjKSDHA3I8M+0LSQRnms25FvtdNLRxET0nY6IB3tPJ1Zj5/tYKW057XymEpXa88HOo/lcyC96Fj+Oo0sD+2ASrXoJSHXnEa1CUxzKu/3v9DDtXJkVROg9xJSxU0F/E8H0uvYb3AjS9QSlClOaUgGDZnxZGD/ALgs9Zd9Mahl5sfVQFaCstA7Lihi2Y3mLFbj7Xk8X06A6kxGmrJn2nFrHvBBh/E0fswQAG8SCn97nQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: default
    type: Opaque
